name: image_crop
description: A flutter plugin to crop image on iOS and Android. It processes image files off main thread natively. The plugin provides a Crop widget to display image cropping to a user.
version: 0.4.1
homepage: https://github.com/VolodymyrLykhonis/image_crop

environment:
  #Especifica as versões do Dart SDK que o aplicativo suporta
  sdk: ">=3.3.1 <4.0.0"
  #Especifica a versao do Flutter SDK que o aplicativo suporta
  flutter: ">=3.19.3"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.lykhonis.imagecrop
        pluginClass: ImageCropPlugin
      ios:
        pluginClass: ImageCropPlugin
